# Generated by Django 4.1.6 on 2023-04-08 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='temperature_db2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(default=40)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='temperature_db',
            new_name='temperature_db1',
        ),
    ]
