# Generated by Django 4.1.6 on 2023-04-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_temperature_db2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature_db2',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
