# Generated by Django 4.1.6 on 2023-04-08 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_temperature_db2_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature_db2',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
