# Generated by Django 4.1.6 on 2023-04-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_temperature_db2_datetime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='temperature_db1',
            new_name='temperature_db',
        ),
    ]
